### ISSUE TITLE
IM clock?

### ISSUE THREAD

**Issue by mhdelta** [h3ct0rjs/ComputerArchitecture#1]
Muchachos, en el dibujo hecho en clase la IM aparecia asincrona, pero por el rst la puse sincrona, nos generara eso algun problema mas adelante, ustedes que opinan?

**Comment by h3ct0rjs** [comment]
@mhdelta Bueno pues no creo realmente que genere un problema , me parece que es hasta mas seguro el diseño asi con una señal de reloj dado que todas las operaciones estan sincronizadas, aun asi yo le pregunto ahora en clase al profe @kala855.

**Comment by h3ct0rjs** [comment]
@mhdelta Hable con el profesor hoy y lo mas recomendado para esta IM y esta entrega es que tiene que ser asincrona para evitar unos delays.Eliminemos lo del clock de la IM. Cuando haga ese commit referencielo a este issue y lo cierra.

**Comment by h3ct0rjs** [comment]
@mhdelta como usted sabe este repo es completamente abierto y tiene una licencia MIT, no se si usted conozca lo del hacktoberfest pero pienso en que podriamos construir este procesador como ejemplo para otros, asi que agregare un nuevo level llamado hacktoberfest. para mas info ver https://blog.digitalocean.com/hacktoberfest-2017/?utm_source=local&utm_medium=email&utm_campaign=Hacktoberfest2017
