### ISSUE TITLE
Module Integration, First Delivery

### ISSUE THREAD

**Issue by h3ct0rjs** [h3ct0rjs/ComputerArchitecture#2]
Hi @mhdelta , 
We need to set the date for our meeting. choose the day and the hour to check my calendar, the idea is to integrate all the modules.

@marincami remember that you should finish the module.

**Comment by mhdelta** [comment]
@h3ct0rjs @carlos4rias We urgently need the RF :) , we can integrate it Monday before 11AM, if you guys can.

**Comment by h3ct0rjs** [comment]
@mhdelta Sorry at that time I'm in class, I could be in the following schedules : 
Monday After 3pm 
Tuesday from 1 to 2 pm 
Wednesday from 6 am to 9am. 
next days after 6pm. 
@marincami Cami we need your Register file.

**Comment by mhdelta** [comment]
@carlos4rias @marincami yo hago pues el rf y ustedes integran. en un rato lo subo

**Comment by h3ct0rjs** [comment]
Seguiremos usando español debido a la solicitud de @marincami . Necesitamos empezar a planear la entrega 2 que es dentro de 15 dias.

**Comment by h3ct0rjs** [comment]
@marincami  Confirmenos cuando realice la prueba de integracion de la primera entrega y cierras este issue. Voy a abrir y crear dos issue. Por favor los commits que hagamos referenciemolos aca en los issues para tener seguimiento.

**Comment by h3ct0rjs** [comment]
Primera entrega esta hecha. Funciona ok.  La referencia es 
 670aa3193bbbd4b7d3541ab79710037208e5f15a
